local module = {
	[1] = {
		["Title"] = "Question 1",
		["Answers"] = {
			["Answer 1 Correct"] = true,
			["Answer 2"] = false,
			["Answer 3"] = false,
			["Answer 4"] = false,
		}
	},
	[2] = {
		["Title"] = "Question 2",
		["Answers"] = {
			["Answer 1"] = false,
			["Answer 2"] = false,
			["Answer 3 Correct"] = true,
			["Answer 4"] = false,
		}
	},
	[3] = {
		["Title"] = "Question 3",
		["Answers"] = {
			["Answer 1"] = false,
			["Answer 2 Correct"] = true,
			["Answer 3"] = false,
			["Answer 4"] = false,
		}
	},
	[4] = {
		["Title"] = "Question 4",
		["Answers"] = {
			["Answer 1"] = false,
			["Answer 2"] = false,
			["Answer 3"] = false,
			["Answer 4 Correct"] = true,
		}
	},
	[5] = {
		["Title"] = "Question 5",
		["Answers"] = {
			["Answer 1 Correct"] = true,
			["Answer 2"] = false,
			["Answer 3"] = false,
			["Answer 4"] = false,
		}
	},
	[6] = {
		["Title"] = "Question 6",
		["Answers"] = {
			["Answer 1"] = false,
			["Answer 2 Correct"] = true,
			["Answer 3"] = false,
			["Answer 4"] = false,
		}
	},
	[7] = {
		["Title"] = "Question 7",
		["Answers"] = {
			["Answer 1"] = false,
			["Answer 2"] = false,
			["Answer 3 Correct"] = true,
			["Answer 4"] = false,
		}
	},
	[8] = {
		["Title"] = "Question 8",
		["Answers"] = {
			["Answer 1"] = false,
			["Answer 2"] = false,
			["Answer 3"] = false,
			["Answer 4 Correct"] = true,
		}
	},
	[9] = {
		["Title"] = "Question 9",
		["Answers"] = {
			["Answer 1 Correct"] = true,
			["Answer 2"] = false,
			["Answer 3"] = false,
			["Answer 4"] = false,
		}
	},
	[10] = {
		["Title"] = "Question 10",
		["Answers"] = {
			["Answer 1"] = false,
			["Answer 2 Correct"] = true,
			["Answer 3"] = false,
			["Answer 4"] = false,
		}
	},
	[11] = {
		["Title"] = "Question 11",
		["Answers"] = {
			["Answer 1"] = false,
			["Answer 2"] = false,
			["Answer 3 Correct"] = true,
			["Answer 4"] = false,
		}
	},
	[12] = {
		["Title"] = "Question 12",
		["Answers"] = {
			["Answer 1"] = false,
			["Answer 2"] = false,
			["Answer 3"] = false,
			["Answer 4 Correct"] = true,
		}
	},
	[13] = {
		["Title"] = "Question 13",
		["Answers"] = {
			["Answer 1 Correct"] = true,
			["Answer 2"] = false,
			["Answer 3"] = false,
			["Answer 4"] = false,
		}
	},
	[14] = {
		["Title"] = "Question 14",
		["Answers"] = {
			["Answer 1"] = false,
			["Answer 2 Correct"] = true,
			["Answer 3"] = false,
			["Answer 4"] = false,
		}
	},
	[15] = {
		["Title"] = "Question 15",
		["Answers"] = {
			["Answer 1"] = false,
			["Answer 2"] = false,
			["Answer 3 Correct"] = true,
			["Answer 4"] = false,
		}
	},
	[16] = {
		["Title"] = "Question 16",
		["Answers"] = {
			["Answer 1"] = false,
			["Answer 2"] = false,
			["Answer 3"] = false,
			["Answer 4 Correct"] = true,
		}
	},
	[17] = {
		["Title"] = "Question 17",
		["Answers"] = {
			["Answer 1 Correct"] = true,
			["Answer 2"] = false,
			["Answer 3"] = false,
			["Answer 4"] = false,
		}
	},
	[18] = {
		["Title"] = "Question 18",
		["Answers"] = {
			["Answer 1"] = false,
			["Answer 2 Correct"] = true,
			["Answer 3"] = false,
			["Answer 4"] = false,
		}
	},
	[19] = {
		["Title"] = "Question 19",
		["Answers"] = {
			["Answer 1"] = false,
			["Answer 2"] = false,
			["Answer 3 Correct"] = true,
			["Answer 4"] = false,
		}
	},
	[20] = {
		["Title"] = "Question 20",
		["Answers"] = {
			["Answer 1"] = false,
			["Answer 2"] = false,
			["Answer 3"] = false,
			["Answer 4 Correct"] = true,
		}
	},
	[21] = {
		["Title"] = "Question 21",
		["Answers"] = {
			["Answer 1 Correct"] = true,
			["Answer 2"] = false,
			["Answer 3"] = false,
			["Answer 4"] = false,
		}
	},
	[22] = {
		["Title"] = "Question 22",
		["Answers"] = {
			["Answer 1"] = false,
			["Answer 2 Correct"] = true,
			["Answer 3"] = false,
			["Answer 4"] = false,
		}
	},
	[23] = {
		["Title"] = "Question 23",
		["Answers"] = {
			["Answer 1"] = false,
			["Answer 2"] = false,
			["Answer 3 Correct"] = true,
			["Answer 4"] = false,
		}
	},
	[24] = {
		["Title"] = "Question 24",
		["Answers"] = {
			["Answer 1"] = false,
			["Answer 2"] = false,
			["Answer 3"] = false,
			["Answer 4 Correct"] = true,
		}
	},
	[25] = {
		["Title"] = "Question 25",
		["Answers"] = {
			["Answer 1 Correct"] = true,
			["Answer 2"] = false,
			["Answer 3"] = false,
			["Answer 4"] = false,
		}
	},
	[26] = {
		["Title"] = "Question 26",
		["Answers"] = {
			["Answer 1"] = false,
			["Answer 2 Correct"] = true,
			["Answer 3"] = false,
			["Answer 4"] = false,
		}
	},
	[27] = {
		["Title"] = "Question 27",
		["Answers"] = {
			["Answer 1"] = false,
			["Answer 2"] = false,
			["Answer 3 Correct"] = true,
			["Answer 4"] = false,
		}
	},
	[28] = {
		["Title"] = "Question 28",
		["Answers"] = {
			["Answer 1"] = false,
			["Answer 2"] = false,
			["Answer 3"] = false,
			["Answer 4 Correct"] = true,
		}
	},
	[29] = {
		["Title"] = "Question 29",
		["Answers"] = {
			["Answer 1 Correct"] = true,
			["Answer 2"] = false,
			["Answer 3"] = false,
			["Answer 4"] = false,
		}
	},
	[30] = {
		["Title"] = "Question 30",
		["Answers"] = {
			["Answer 1"] = false,
			["Answer 2 Correct"] = true,
			["Answer 3"] = false,
			["Answer 4"] = false,
		}
	},
	[31] = {
		["Title"] = "Question 31",
		["Answers"] = {
			["Answer 1"] = false,
			["Answer 2"] = false,
			["Answer 3 Correct"] = true,
			["Answer 4"] = false,
		}
	},
	[32] = {
		["Title"] = "Question 32",
		["Answers"] = {
			["Answer 1"] = false,
			["Answer 2"] = false,
			["Answer 3"] = false,
			["Answer 4 Correct"] = true,
		}
	},
	[33] = {
		["Title"] = "Question 33",
		["Answers"] = {
			["Answer 1 Correct"] = true,
			["Answer 2"] = false,
			["Answer 3"] = false,
			["Answer 4"] = false,
		}
	},
	[34] = {
		["Title"] = "Question 34",
		["Answers"] = {
			["Answer 1"] = false,
			["Answer 2 Correct"] = true,
			["Answer 3"] = false,
			["Answer 4"] = false,
		}
	},
	[35] = {
		["Title"] = "Question 35",
		["Answers"] = {
			["Answer 1"] = false,
			["Answer 2"] = false,
			["Answer 3 Correct"] = true,
			["Answer 4"] = false,
		}
	}
}

return module
